//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_prestamos
    {
        public int id_detalle_prestamos { get; set; }
        public Nullable<int> id_libro { get; set; }
        public Nullable<int> id_cab_prestamos { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual cabecera_prestamos cabecera_prestamos { get; set; }
        public virtual libro libro { get; set; }
    }
}
